name: Keep App Alive

on:
  schedule:
    # Se ejecuta cada 2 horas (minuto 0, cada 2 horas)
    - cron: "0 */2 * * *"
  workflow_dispatch: # Esto permite que lo pruebes manualmente con un bot√≥n

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        # Reemplaza la URL de abajo con la de tu app real
        run: curl -I https://decoy-troy.streamlit.app/
